preset: laravel

enabled:
  - concat_with_spaces
  - align_double_arrow

disabled:
  - phpdoc_summary
  - concat_without_spaces
  - not_operator_with_successor_space
  - no_multiline_whitespace_around_double_arrow

finder:
  not-name:
    - "_migration_helper.php"
